FROM node:lts-alpine As builder
WORKDIR /build
COPY package*.json tsconfig.json ./
RUN npm ci
COPY . .
RUN npm run build


FROM node:lts-alpine As runner
WORKDIR /app
COPY --from=builder /build ./
CMD ["npm", "run", "start:dev"]
